-- migrations/0021_task_number.sql — a short, human task key: FN-42 (TASK-053).
--
-- Borrowed from Jira and Linear, whose keys ("PROJ-123") are what people say out loud, type in
-- a chat and see in an email subject. A uuid is none of those things. Jira matches a reply to
-- its issue by the key in the subject first and the In-Reply-To header second; the email
-- pipeline does the same, so the key has to exist on every task, old ones included.
--
-- An identity column: Postgres numbers the existing rows when the column is added, and every
-- new task gets the next number. Never reused, never edited.

alter table task add column if not exists task_number bigint generated by default as identity;
create unique index if not exists task_task_number_key on task (task_number);
